[secrets]
OPENAI_API_KEY="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"

import os
print(os.getcwd())  # Kiểm tra thư mục hiện tại
print(st.secrets)   # Kiểm tra nội dung secrets
